# H2
spring.h2.console:
  enabled: true
  path: /h2

# Datasource 1
spring.datasource:
  url: jdbc:h2:./src/main/resources/testdb;MV_STORE=FALSE;AUTO_SERVER=TRUE
  username: sa
  password:
  driver-class-name: org.h2.Driver
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update

#Logger
logging:
  file:
    path: /var/logs/TaskerLogs.log
  level:
    root: WARN
      org.springframework:
        security: DEBUG


